export const LOGIN_PAGE = [
  '<!doctype html><html lang="pl"><head><meta charset="utf-8" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1" />',
  '<title>Omni - kod dostepu</title>',
  '<style>body{margin:0;height:100vh;display:flex;align-items:center;justify-content:center;background:#0b0f14;color:#e6edf6;font-family:system-ui,Arial,sans-serif}',
  '.box{background:#111823;border:1px solid #1e2a3a;border-radius:16px;padding:26px;width:320px;text-align:center}',
  'h1{font-size:18px;margin:0 0 6px}p{color:#8ba0b8;font-size:13px;margin:0 0 16px}',
  'input{width:100%;background:#0b1119;border:1px solid #23324a;color:#fff;border-radius:10px;padding:12px;font-size:16px;text-align:center}',
  'button{margin-top:12px;width:100%;background:#2563eb;border:0;color:#fff;border-radius:10px;padding:12px;font-size:15px;cursor:pointer}',
  '.err{color:#ef4444;font-size:12px;margin-top:10px;min-height:16px}</style></head><body>',
  '<div class="box"><h1>Omni</h1><p>Podaj kod dostepu, aby wejsc.</p>',
  '<input id="code" type="password" inputmode="numeric" placeholder="Kod" />',
  '<button id="go">Wejdz</button><div class="err" id="err"></div></div>',
  '<script>function go(){var c=document.getElementById("code").value;',
  'fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:c})})',
  '.then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};});})',
  '.then(function(x){if(x.ok){location.href="/";}else{document.getElementById("err").textContent=x.j.error||"Zly kod";}})',
  '.catch(function(){document.getElementById("err").textContent="Blad polaczenia";});}',
  'document.getElementById("go").addEventListener("click",go);',
  'document.getElementById("code").addEventListener("keydown",function(e){if(e.key==="Enter"){go();}});</script></body></html>',
].join('');
